Repository AitZak/projet_II, pull requests merged in 2020-03, with the labels that each got.

#37 add communication dashboard and review feature
  src/Controller/ApprovalController.php
  src/Controller/CommunicatorController.php
  src/Controller/ContentController.php
  src/Entity/Approval.php
  src/Entity/Content.php
  src/Entity/Publication.php
  src/Entity/SocialNetwork.php
  src/Entity/User.php
  src/Manager/ApprovalManager.php
  src/Manager/ContentManager.php
  src/Repository/ApprovalRepository.php
  src/Repository/ContentRepository.php
  src/Repository/PublicationRepository.php
  templates/communicator/dashboard.html.twig
  templates/content/show.html.twig
Labels: enhancement

#35 add comment CRUD
  src/Controller/CommentController.php
  src/Controller/ContentController.php
  src/Entity/Comment.php
  src/Form/CommentType.php
  templates/comment/_delete_form.html.twig
  templates/comment/_form.html.twig
  templates/comment/edit.html.twig
  templates/comment/index.html.twig
  templates/comment/new.html.twig
  templates/comment/show.html.twig
  templates/content/show.html.twig
Labels: enhancement

#36 Add/front/content/edtion
  public/css/Style.css
  templates/content/_delete_form.html.twig
  templates/content/_form.html.twig
  templates/content/edit.html.twig
  templates/content/index.html.twig
  templates/content/new.html.twig
  templates/content/show.html.twig
  templates/main/footer.html.twig
  templates/main/head.html.twig
Labels: enhancement

#46 improve review module
  src/Controller/ApprovalController.php
  src/Controller/ContentController.php
  src/Manager/ApprovalManager.php
  templates/content/show.html.twig
Labels: improvement

#50 fix button review
  templates/content/show.html.twig
Labels: bug

#48 add personal pages
  src/Controller/UserController.php
  src/Manager/ApprovalManager.php
  src/Manager/ContentManager.php
  templates/main/header.html.twig
  templates/user/publications.html.twig
  templates/user/reviews.html.twig
  templates/user/submissions.html.twig
Labels: enhancement

#51 add controlon content edition
  src/Controller/ContentController.php
  templates/content/_delete_form.html.twig
  templates/content/index.html.twig
Labels: enhancement

#52 add navigation rights by role
  config/packages/security.yaml
  src/Controller/ApprovalController.php
  src/Controller/CommentController.php
  src/Controller/CommunicatorController.php
  src/Controller/ContentController.php
  src/Controller/SocialNetworkController.php
  src/Controller/UserController.php
  src/Form/UserType.php
  src/Manager/ApprovalManager.php
  templates/main/error_connection.html.twig
  templates/main/error_role.html.twig
  templates/main/header.html.twig
Labels: enhancement

#54 fix docker compose bug
  docker-compose.yml
Labels: bug

#55 Addfront comment
  .env.dist
  public/css/clean-blog.min.css
  public/css/comment.css
  public/css/sb-admin-2.css
  public/css/sb-admin-2.min.css
  public/js/sb-admin-2.js
  public/js/sb-admin-2.min.js
  public/js/sb-admin-3.min.js
  templates/Security/login.html.twig
  templates/comment/_delete_form.html.twig
  templates/comment/_form.html.twig
  templates/comment/comment.html.twig
  templates/comment/edit.html.twig
  templates/comment/index.html.twig
  templates/comment/show.html.twig
  templates/communicator/dashboard.html.twig
  templates/content/_form.html.twig
  templates/content/edit.html.twig
  templates/content/show.html.twig
  templates/main/head.html.twig
  templates/main/header.html.twig
  templates/main/js.html.twig
  templates/social_network/_delete_form.html.twig
  templates/social_network/_form.html.twig
  templates/social_network/edit.html.twig
  templates/social_network/index.html.twig
  templates/social_network/show.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/publications.html.twig
  templates/user/reviews.html.twig
  templates/user/show.html.twig
  templates/user/submissions.html.twig
Labels: enhancement

#57 fix deletion of user and content
  src/Controller/ContentController.php
  src/Controller/UserController.php
  src/Entity/Approval.php
  src/Form/UserType.php
  src/Manager/ApprovalManager.php
  src/Manager/CommentManager.php
  src/Manager/ContentManager.php
  src/Manager/ModificationManager.php
  src/Manager/PublicationManager.php
  src/Manager/UserManager.php
  src/Repository/CommentRepository.php
  src/Repository/ModificationRepository.php
Labels: bug

#60 Addfront user
  templates/content/index.html.twig
  templates/content/show.html.twig
  templates/social_network/index.html.twig
  templates/user/_form.html.twig
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: bug

#59 add my profile page
  templates/content/show.html.twig
  templates/main/header.html.twig
  templates/user/_form.html.twig
Labels: bug, enhancement

#61 add dataTables to user index and content index
  templates/content/index.html.twig
  templates/main/head.html.twig
  templates/main/js.html.twig
  templates/user/index.html.twig
Labels: enhancement

#62 fix buttons approve and reject
  templates/content/show.html.twig
Labels: bug

#63 do not accept own content
  templates/content/show.html.twig
Labels: enhancement

#65 fix All Content Button
  templates/comment/index.html.twig
  templates/comment/new.html.twig
  templates/comment/show.html.twig
  templates/content/index.html.twig
  templates/content/show.html.twig
  templates/main/header.html.twig
  templates/social_network/edit.html.twig
  templates/social_network/index.html.twig
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: bug

#64 fix dataTable and scroll navbar
  templates/base.html.twig
  templates/content/index.html.twig
  templates/user/index.html.twig
Labels: bug

#67 fix buttons redirection
  src/Controller/ContentController.php
  src/Controller/UserController.php
  templates/content/index.html.twig
  templates/content/show.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/show.html.twig
  templates/user/submissions.html.twig
Labels: bug, enhancement

#68 fix bug when user is not connected
  templates/main/header.html.twig
Labels: bug

#69 FixBug/content-navbar-edituser
  templates/content/show.html.twig
  templates/main/error_connection.html.twig
  templates/main/header.html.twig
  templates/user/_delete_form.html.twig
  templates/user/edit.html.twig
  templates/user/reviews.html.twig
Labels: bug

#70 fix condition user connected
  templates/main/header.html.twig
Labels: bug

#73 back route home
  src/Controller/HomeController.php
  templates/content/index.html.twig
  templates/home/index.html.twig
Labels: enhancement

#74 Addlast bug
  templates/approval/show.html.twig
  templates/communicator/dashboard.html.twig
  templates/content/show.html.twig
  templates/home/index.html.twig
  templates/social_network/_form.html.twig
  templates/social_network/new.html.twig
  templates/social_network/show.html.twig
  templates/user/new.html.twig
Labels: bug

#75 fix home acces to content show
  src/Controller/ContentController.php
  templates/main/header.html.twig
Labels: bug

#76 add front new user
  templates/content/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/new.html.twig
Labels: bug

#77 fix dropdown mon espace
  templates/main/header.html.twig
Labels: bug

#78 fix_bug
  src/Controller/PublicationController.php
  templates/content/index.html.twig
  templates/content/show.html.twig
  templates/main/header.html.twig
  templates/social_network/index.html.twig
  templates/user/publications.html.twig
Labels: bug
